name: centos-7.9.2009
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/centos-7.9.2009.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login in AliYun Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNHUB_USERNAME }}
          password: ${{ secrets.ALIYUNHUB_TOKEN }}

      - name: Build and push
        run: |
          docker pull centos:7.9.2009
          docker tag centos:7.9.2009 registry.cn-hangzhou.aliyuncs.com/jaronnie/centos:7.9.2009
          docker push registry.cn-hangzhou.aliyuncs.com/jaronnie/centos:7.9.2009
