name: elasticsearch-v6.8.24
on:
  push:
    branches:
      - 'main'
    paths:
      - 'elasticsearch/v6.8.24/**'  
      - '.github/workflows/elasticsearch-v6.8.24-arm64.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2            

      - name: Login in Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./elasticsearch/v6.8.24/Dockerfile
          platforms: |
            linux/arm64
          push: true
          tags: |
            jaronnie/elasticsearch:v6.8.24