name: redis-v6.2.14
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/etcd-v3.5.14.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login in AliYun Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNHUB_USERNAME }}
          password: ${{ secrets.ALIYUNHUB_TOKEN }}

      - name: Build and push
        run: |
          docker pull bitnami/etcd:3.5.14
          docker tag bitnami/etcd:3.5.14 registry.cn-hangzhou.aliyuncs.com/jaronnie/etcd:3.5.14
          docker push registry.cn-hangzhou.aliyuncs.com/jaronnie/etcd:3.5.14