name: java-maven-3.6.3-openjdk-8u322
on:
  push:
    paths:
      - ./java/maven-3.6.3-openjdk-8u322/Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Login in Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker pull and push
        run: |
          docker build -t jaronnie/java:maven-3.6.3-oepnjdk-8u322
          docker push jaronnie/java:maven-3.6.3-openjdk-8u321