name: java-maven-3.6.3-openjdk-8u322
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login in Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check Dockerfile changes
        id: file_changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            changes:
              - 'java/maven-3.6.3-openjdk-8u322/Dockerfile'

      - name: Docker build and push
        run: |
          if [ "${{ steps.file_changes.outputs.changes }}" == "true" ]; then
            docker build -t jaronnie/java:maven-3.6.3-openjdk-8u322 -f java/maven-3.6.3-openjdk-8u322/Dockerfile .
            docker push jaronnie/java:maven-3.6.3-openjdk-8u322
          else
            echo "No changes in Dockerfile. Skipping Docker build and push."
          fi