name: nexus3-v3.53.0
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/nexus3-v3.53.0.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login in AliYun Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNHUB_USERNAME }}
          password: ${{ secrets.ALIYUNHUB_TOKEN }}

      - name: Build and push
        run: |
          docker pull sonatype/nexus3:3.53.0
          docker tag sonatype/nexus3:3.53.0 registry.cn-hangzhou.aliyuncs.com/jaronnie/sonatype/nexus3:3.53.0
          docker push registry.cn-hangzhou.aliyuncs.com/jaronnie/sonatype/nexus3:3.53.0