name: metrics-server-v0.5.2
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/nfs-subdir-external-provisioner-v4.0.2.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2            

      - name: Login in Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          docker pull registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          docker tag registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2 jaronnie/nfs-subdir-external-provisioner:v4.0.2
          docker push jaronnie/nfs-subdir-external-provisioner:v4.0.2