name: nginx-1.26-alpine
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/nginx-1.26-alpine.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login in AliYun Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNHUB_USERNAME }}
          password: ${{ secrets.ALIYUNHUB_TOKEN }}

      - name: Build and push
        run: |
          docker pull nginx:1.26-alpine
          docker tag nginx:1.26-alpine registry.cn-hangzhou.aliyuncs.com/jaronnie/nginx:1.26-alpine
          docker push registry.cn-hangzhou.aliyuncs.com/jaronnie/nginx:1.26-alpine
