name: node-16
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/node-16.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login in AliYun Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNHUB_USERNAME }}
          password: ${{ secrets.ALIYUNHUB_TOKEN }}

      - name: Build and push
        run: |
          docker pull node:16
          docker tag node:16 registry.cn-hangzhou.aliyuncs.com/jaronnie/node:16
          docker push registry.cn-hangzhou.aliyuncs.com/jaronnie/node:16
