name: node-20.12.2-openssh-pnpm
on:
  push:
    branches:
      - 'main'
    paths:
      - 'node/node-20.12.2-openssh-pnpm/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login in AliYun Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNHUB_USERNAME }}
          password: ${{ secrets.ALIYUNHUB_TOKEN }}

      - name: Docker build and push
        run: |
            docker build -t registry.cn-hangzhou.aliyuncs.com/jaronnie/node-20.12.2-openssh-pnpm -f node/node-20.12.2-openssh-pnpm/Dockerfile .
            docker push registry.cn-hangzhou.aliyuncs.com/jaronnie/node-20.12.2-openssh-pnpm
